[project]
name = "ytconnect"
description = "Gets YouTuber information"
version = "0.0.1"
authors = [
    { name = "Knightbot63", email = "Knightbot63@whatever.email" }
]
dependencies = [
    "requests"
]
